name: context-variables-demo
on:
  push
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Use Context varibales
      run: |
        echo "This workflow is triggered by ${{github.actor}}"
        echo "This repository name is ${{github.respository}}"
        echo "This branch is ${{github.ref_name}}
    - name: print all variables under github
      run: echo "${{toJson(github)}}"
    - name: print environmet variables
      run: | 
        printenv
        echo "$GIT_HUB_SHA"

        
        
      
