name: Inputs Demo
on:
  workflow-dispatch:
    inputs:
      environment:
        description: Choose environment to Deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod
      artifact_tag:
        description: Choose git tag to deploy
        required: true
jobs:
  inputs-demo:
    runs_on: ubuntu-latest
      steps:
        - name: Deploy the app
          run: echo "Deploy the application to ${{inputs.environment}}"
          run: echo "Deploying the artifact ${{inputs.artifact_tag}} of the application to ${{ inputs.environment}}"
          

        
