name: HelloWorld
# on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello step
        run: |
          echo "hi bharath" 
          echo "focus on GHA"
          echo "Hello, ${{ vars.MY_NAME}}"
          echo "Docker password is, ${{ secrets.DOCKER_PASSWORD}}"
          echo "User Secret is, ${{secrets.USER_ID}}"

