name: Multijob
on: workflow_dispatch
jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "A Demo Build"
  test:  
    runs-on: ubuntu-latest
    steps:
      - name: Testing Phase
        run: echo "Running test cases"
  deploy:  
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the App
        run: echo "Deploy the application"      
