name: output-demo
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.step1.outputs.version}}
    steps:
      - name: Build step
        run: |
          echo "version=0.0.1" >> $GITHUB_OUTPUT
          echo "Contents of \$GITHUB_OUTPUT:"
          cat "$GITHUB_OUTPUT"
        id: step1
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy the Application
      run: echo "We are deploying the app with version ${{needs.build.outputs.version}}"
